from __future__ import annotations

DEFAULT_STATE_FILE = ".dispatcher/state.json"
DEFAULT_LOG_DIR = ".dispatcher/logs"
DEFAULT_LABEL = "automate"
DEFAULT_BASE_BRANCH = "main"
DEFAULT_BRANCH_PREFIX = "feat/issue-"
DEFAULT_POLL_INTERVAL_SECONDS = 120.0

BANNED_AGENT_FLAGS = {
    "--allow-dangerously-skip-permissions",
    "--dangerously-bypass-approvals-and-sandbox",
    "--dangerously-skip-permissions",
    "--full-auto",
    "--yolo",
    "-y",
}

GEMINI_WORKTREE_ALLOWED_TOOLS = (
    "activate_skill",
    "list_directory",
    "read_file",
    "read_many_files",
    "glob",
    "grep_search",
    "web_fetch",
    "run_shell_command",
    "run_shell_command(bash)",
    "run_shell_command(bun)",
    "run_shell_command(cp)",
    "run_shell_command(dirname)",
    "run_shell_command(find)",
    "run_shell_command(git)",
    "run_shell_command(grep)",
    "run_shell_command(ls)",
    "run_shell_command(mkdir)",
    "run_shell_command(npm)",
    "run_shell_command(pnpm)",
    "run_shell_command(pwd)",
    "run_shell_command(rsync)",
    "run_shell_command(sh)",
    "run_shell_command(test)",
    "run_shell_command(yarn)",
)

CLAUDE_PLAN_ALLOWED_TOOLS = (
    "Read",
    "Glob",
    "Grep",
    "Write(.ai/assets/branches/**)",
    "Edit(.ai/assets/branches/**)",
    "MultiEdit(.ai/assets/branches/**)",
    "Bash(gh issue list *)",
    "Bash(gh issue view *)",
    "Bash(gh pr checks *)",
    "Bash(gh pr diff *)",
    "Bash(gh pr list *)",
    "Bash(gh pr status *)",
    "Bash(gh pr view *)",
    "Bash(gh repo list *)",
    "Bash(gh repo view *)",
    "Bash(gh search code *)",
    "Bash(gh search commits *)",
    "Bash(gh search issues *)",
    "Bash(gh search prs *)",
    "Bash(gh search repos *)",
    "Bash(git branch *)",
    "Bash(git diff *)",
    "Bash(git log *)",
    "Bash(git ls-files *)",
    "Bash(git status *)",
    "Bash(find *)",
    "Bash(ls *)",
    "Bash(pwd)",
)

CLAUDE_REVIEW_ALLOWED_TOOLS = (
    "Read",
    "Glob",
    "Grep",
    "Bash(git diff *)",
    "Bash(git log *)",
    "Bash(git ls-files *)",
    "Bash(git status *)",
    "Bash(find *)",
    "Bash(ls *)",
    "Bash(pwd)",
)

CLAUDE_PLAN_DISALLOWED_TOOLS = (
    "Bash(chmod *)",
    "Bash(chown *)",
    "Bash(dd *)",
    "Bash(dropdb *)",
    "Bash(gh api * --method DELETE *)",
    "Bash(gh api * --method PATCH *)",
    "Bash(gh api * --method POST *)",
    "Bash(gh api * -X DELETE *)",
    "Bash(gh api * -X PATCH *)",
    "Bash(gh api * -X POST *)",
    "Bash(gh issue close *)",
    "Bash(gh issue comment *)",
    "Bash(gh issue create *)",
    "Bash(gh issue delete *)",
    "Bash(gh issue develop *)",
    "Bash(gh issue edit *)",
    "Bash(gh issue lock *)",
    "Bash(gh issue pin *)",
    "Bash(gh issue reopen *)",
    "Bash(gh issue transfer *)",
    "Bash(gh pr close *)",
    "Bash(gh pr comment *)",
    "Bash(gh pr create *)",
    "Bash(gh pr edit *)",
    "Bash(gh pr lock *)",
    "Bash(gh pr merge *)",
    "Bash(gh pr ready *)",
    "Bash(gh pr reopen *)",
    "Bash(gh pr review *)",
    "Bash(git branch -D *)",
    "Bash(git branch --delete --force *)",
    "Bash(git clean *)",
    "Bash(git push --delete *)",
    "Bash(git push --force *)",
    "Bash(git push --force-with-lease *)",
    "Bash(git push -f *)",
    "Bash(git reset --hard *)",
    "Bash(kubectl delete *)",
    "Bash(mv *)",
    "Bash(psql *DROP*)",
    "Bash(rm *)",
    "Bash(rsync --delete *)",
)
